src/main/kotlin/trik/testsys/webclient/controller/AccessController.kt
src/main/kotlin/trik/testsys/webclient/controller/AdminController.kt
src/main/kotlin/trik/testsys/webclient/controller/StudentController.kt
src/main/kotlin/trik/testsys/webclient/entity/Group.kt

- Added access fields to group
- Added endpoint to admin's controller for changing group access
- Added validating access to group

3 openning clossing groups

---

src/main/kotlin/trik/testsys/webclient/controller/DeveloperController.kt
src/main/kotlin/trik/testsys/webclient/controller/StudentController.kt
src/main/kotlin/trik/testsys/webclient/entity/Task.kt
src/main/kotlin/trik/testsys/webclient/service/TaskService.kt

- Added deadline field to task entity
- Added changing task deadline
- Added validating task deadline before uploading solution

4 tasks deadline

---

src/main/kotlin/trik/testsys/core/utils/l10n/L10nCode.kt
src/main/kotlin/trik/testsys/core/utils/l10n/localizer/DefaultLocalizer.kt
src/main/kotlin/trik/testsys/core/utils/l10n/localizer/Localizer.kt
src/main/resources/application.yml

Added classes for localization

TWC-2 Identify core abstractions in the system

---

Dockerfile
build.gradle.kts
src/main/kotlin/trik/testsys/webclient/controller/impl/user/developer/DeveloperTaskFileController.kt
src/main/kotlin/trik/testsys/webclient/controller/impl/user/superuser/SuperUserAdminController.kt
src/main/kotlin/trik/testsys/webclient/controller/impl/user/superuser/SuperUserAdminsController.kt
src/main/kotlin/trik/testsys/webclient/controller/impl/user/superuser/SuperUserDeveloperController.kt
src/main/kotlin/trik/testsys/webclient/controller/impl/user/superuser/SuperUserDevelopersController.kt
src/main/kotlin/trik/testsys/webclient/controller/impl/user/superuser/SuperUserJudgeController.kt
src/main/kotlin/trik/testsys/webclient/controller/impl/user/superuser/SuperUserJudgesController.kt
src/main/kotlin/trik/testsys/webclient/entity/impl/TaskFile.kt
src/main/kotlin/trik/testsys/webclient/entity/impl/TaskFileAudit.kt
src/main/kotlin/trik/testsys/webclient/repository/TaskFileAuditRepository.kt
src/main/kotlin/trik/testsys/webclient/service/FileManager.kt
src/main/kotlin/trik/testsys/webclient/service/entity/impl/TaskFileAuditService.kt
src/main/kotlin/trik/testsys/webclient/service/impl/FileManagerImpl.kt
src/main/kotlin/trik/testsys/webclient/view/impl/AdminCreationView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/DeveloperCreationView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/JudgeCreationView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/SuperUserView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/TaskFileAuditCreationView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/TaskFileAuditView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/TaskFileView.kt
src/main/resources/templates/developer/taskFile.html
src/main/resources/templates/developer/taskFiles.html
src/main/resources/templates/fragments/entity/superuser.html
src/main/resources/templates/superuser/admins.html
src/main/resources/templates/superuser/developers.html
src/main/resources/templates/superuser/emergency-messages.html
src/main/resources/templates/superuser/judges.html

- Added viewing/creating Viewers/Admins/Developers/Judges
- Added auditing TaskFile entities

2.1.0 features

---

src/main/kotlin/trik/testsys/grading/BalancingGraderService.kt

(cherry picked from commit c8dc8d8f5b88eb4a0f499f67595c4e7d36d33d49)

Applied patch

---

.gitmodules
README.md

(cherry picked from commit f2e7cb7ca43944ca76e3807a860138d258873ca7)

Updated url to new organization (#51)-2.0-patch

---

.gitmodules
README.md

(cherry picked from commit f2e7cb7ca43944ca76e3807a860138d258873ca7)

Updated url to new organization (#51)-2.4-patch

---

.gitmodules
README.md

(cherry picked from commit f2e7cb7ca43944ca76e3807a860138d258873ca7)

Updated url to new organization (#51)-2.3-patch

---

.gitmodules
Dockerfile
README.md
build.gradle.kts
settings.gradle.kts

(cherry picked from commit a161b5ed7cf0af62c83e6e0043c70da4db2bc531)

fix: Updated project names (#55)-2.0-patch

---

.gitmodules
Dockerfile
README.md
build.gradle.kts
docker-compose.yml
settings.gradle.kts

(cherry picked from commit a161b5ed7cf0af62c83e6e0043c70da4db2bc531)

fix: Updated project names (#55)-2.4-patch

---

.gitmodules
Dockerfile
README.md
build.gradle.kts
docker-compose.yml
settings.gradle.kts

(cherry picked from commit a161b5ed7cf0af62c83e6e0043c70da4db2bc531)

fix: Updated project names (#55)-2.3-patch

---

.github/actions/publish-package/action.yml
.github/workflows/build-and-test.yml

* fix: Updated applied branches
* fix: Updated checking latest tag
* fix: Updated checking latest tag
(cherry picked from commit 93792efcb68dfe10e00bb091f175367c8627d012)

Update pipelines (#59)

---

.github/actions/publish-package/action.yml

(cherry picked from commit 5124f997b252a1006e9ad675737f7e77776e97e1)

fix: Updated pushing latest tag (#63)

---

.github/actions/publish-package/action.yml

(cherry picked from commit 106514ef272e379c441a6088cf8e1f708f8c4080)

fix: Fixed adding var to env (#67)

---

src/main/kotlin/trik/testsys/webclient/controller/impl/user/developer/DeveloperContestController.kt
src/main/kotlin/trik/testsys/webclient/util/LocalDateTimeUtils.kt
src/main/kotlin/trik/testsys/webclient/view/impl/ContestCreationView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/ContestView.kt
src/main/resources/templates/developer/contest.html
src/main/resources/templates/developer/contests.html

(cherry picked from commit 5a5a478f86e3eddaddd9c9866fa4c0bdbaf9444c)

fix: Fixed duration field view (#75)

---

src/main/kotlin/trik/testsys/grading/BalancingGraderService.kt
src/main/resources/application.yml

(cherry picked from commit 3eebd8caed9606767f182a9a8dec6ec424abb7f8)

feat: Added additional logging to BalancingGraderService (#78)

---

src/main/kotlin/trik/testsys/grading/BalancingGraderService.kt

* fix: Wrapped addNode body with try-catch
* fix: Wrapped (re)send job body with try-catch
(cherry picked from commit 531c1de9644bf1eb23c5911e66a07d9d726d4ef9)

Wrapped jobs with try-catch (#81)

---

src/main/kotlin/trik/testsys/webclient/service/startup/runner/impl/GradingInfoParserRunner.kt

(cherry picked from commit b2de33b47f3092f7109d7171d2445d1f62ae4a64)

fix: Updated solution score evaluation (#84)

---

.github/actions/publish-package/action.yml

(cherry picked from commit 7aac7e85fc924575e22d9d69e15810256b28d223)

fix: Fixed workflow (#87)

---

src/main/kotlin/trik/testsys/webclient/controller/impl/user/developer/DeveloperContestController.kt
src/main/kotlin/trik/testsys/webclient/entity/impl/Contest.kt
src/main/kotlin/trik/testsys/webclient/entity/user/impl/Student.kt
src/main/kotlin/trik/testsys/webclient/view/impl/ContestCreationView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/ContestView.kt
src/main/kotlin/trik/testsys/webclient/view/impl/StudentContestView.kt
src/main/resources/static/js/scripts.js
src/main/resources/templates/admin/group.html
src/main/resources/templates/developer/contest.html
src/main/resources/templates/developer/contests.html
src/main/resources/templates/student/contest.html
src/main/resources/templates/student/contests.html

* feat: Added ability to create open-dated contests
* feat: Updated placeholder for duration field
* feat: Updated computing remaining time for contests
(cherry picked from commit 0da3538d13bff5042208461c1aa403c4022ca781)

90 add ability to create open ended contests (#91)
